AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S3 resources for Instagram Automation

Parameters:
  Environment:
    Type: String
    Default: dev
  StackName:
    Type: String
    Default: post-generation-dev

Resources:
  MediaAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackName}-media-assets"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
              - ETag
            Id: S3CORSRuleId1
            MaxAge: 3000
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

Outputs:
  MediaAssetsBucketName:
    Description: "Name of the S3 media assets bucket"
    Value: !Ref MediaAssetsBucket
