AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AppSync API resolvers for Instagram Automation

Parameters:
  Environment:
    Type: String
    Default: dev
  StackName:
    Type: String
    Default: post-generation-dev
  LogLevel:
    Type: String
    Default: INFO
    Description: Log level for Lambda functions
  MediaAssetsBucketName:
    Type: String
    Description: Name of the S3 media assets bucket
  LambdaRoleArn:
    Type: String
    Description: Lambda execution role ARN
  InstagramAppId:
    Type: String
    Description: Instagram App ID
    NoEcho: true
  InstagramAppSecret:
    Type: String
    Description: Instagram App Secret
    NoEcho: true
  GroqApiKey:
    Type: String
    Description: Groq API Key
    NoEcho: true
  HuggingFaceApiKey:
    Type: String
    Description: Hugging Face API Key
    NoEcho: true
  UsersTableName:
    Type: String
    Description: DynamoDB Users table name

Resources:
  AiIntegrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${StackName}-ai-integration"
      CodeUri: handlers/aiIntegration
      Handler: index.handler
      Role: !Ref LambdaRoleArn
      Runtime: nodejs22.x
      Timeout: 900
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: !Ref LogLevel
          S3_BUCKET_NAME: !Ref MediaAssetsBucketName
          INSTAGRAM_APP_ID: !Ref InstagramAppId
          INSTAGRAM_APP_SECRET: !Ref InstagramAppSecret
          GROQ_API_KEY: !Ref GroqApiKey
          HUGGING_FACE_API_KEY: !Ref HuggingFaceApiKey

Outputs:
  AiIntegrationFunctionArn:
    Description: "ARN of the AI Integration function"
    Value: !GetAtt AiIntegrationFunction.Arn
